name: CI_Workflow

on: 
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest #Github Runner Free
        steps: 
            - name: checkout code
              uses: actions/checkout@v4 #clone the code in ubuntu server
            
            - name: Setup Docker
              uses: appleboy/ssh-action@v1.0.3
              with: 
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                  cd /home/ubuntu/node_github_action_cicd
                  git pull origin main
                  npm install
                  npm start                